name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASS}}
      - name: Build and push Docker image
        run: |
            docker build -t sagarts/devops-app:latest .
            docker push sagarts/devops-app:latest
      

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      -name:  pull image from docker hub and run
      run: docker pull sagarts/devops-app:latest
      -name: Delete old container
      run: docker rm -f devops-app || true
      -name: Run new container
      run: docker run -d -p 5000:5000 --name devops-app sagarts/devops-app:latest